### ISSUE TITLE
LOD's is broken with specific mods

### ISSUE THREAD

**Issue by frosthuuuund** [imheavi/Distantly-Optimized#3]
**Describe the bug**
Lod's are broken, i don't know why exactly, I've been waiting a lot amount of time with 13900k and i paid for the whole CPU mode.

**To Reproduce**
Remove Terratonic.
[Install this datapack](https://modrinth.com/datapack/jjthunder-to-the-max)

**Expected behavior**
LOD's should render correctly, since they are distant generated, i guess...

**Screenshots**
![image](https://github.com/imheavi/Distantly-Optimized/assets/174178570/a4a7b2cf-2bb2-46bf-b263-b4ce596a6d52)

**Desktop:**
 - OS: [Windows 11]
 - Version [v5]

**Additional context**

**Comment by frosthuuuund** [comment]
```
[10:14:02] [DH-World Gen Thread[2]/WARN]: Unexpected issue when generating features for chunk at pos [C[-27,-24]], error: [Feature placement].
net.minecraft.class_148: Feature placement
	at net.minecraft.class_2794.method_12102(class_2794.java:377) ~[client-intermediary.jar:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.4-forge-fabric.jar:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.4-forge-fabric.jar:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.4-forge-fabric.jar:?]
	at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.4-forge-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: No chunk exists at [-27, -22]
	at net.minecraft.class_3233.method_8320(class_3233.java:588) ~[client-intermediary.jar:?]
	at net.minecraft.class_3233.method_16358(class_3233.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_5726.method_33388(class_5726.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_5726.method_33009(class_5726.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_5727$class_5728.method_33019(class_5727.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_5727.method_13151(class_5727.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:54) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:357) ~[client-intermediary.jar:?]
	... 8 more
	```

**Comment by imheavi** [comment]
This appears to be an error with Distant Horizons, try submitting an [issue](https://gitlab.com/jeseibel/distant-horizons/-/issues) there/asking in their [Discord].(https://discord.gg/xAB8G4cENx)
